branches:
    only:
        - master

image:
    - Visual Studio 2019

clone_folder: c:\projects\dummy

clone_script:
    - git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    - git checkout -qf %APPVEYOR_REPO_COMMIT%

shallow_clone: true

matrix:
    fast_finish: true

platform:
    - x64

configuration:
    - Release
    
init:
    - set arch=
    - if "%PLATFORM%"=="x64" ( set arch= Win64)
    - if "%PLATFORM%"=="x64" ( set arch2= -A x64)
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" %arch2% )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )

before_build:
    - mkdir build_gl
    - mkdir build_vk
    - cd build_gl
    - cmake .. -G %generator% -DENABLE_OPENCL=OFF -DRENDERER=GL -DENABLE_UNITYBUILD=ON
    - cd ..
    - cd build_vk
    - cmake .. -G %generator% -DENABLE_OPENCL=OFF -DRENDERER=VK -DENABLE_UNITYBUILD=ON
    - cd ..
        
build_script:
    - cmake --build build_gl --target ALL_BUILD --config Release
    - cmake --build build_vk --target DummyApp --config Release

after_build:
    - DummyAppVK --prepare_assets pc --norun
    - 7z a -mx9 dummy_app_%APPVEYOR_BUILD_VERSION%.zip DummyAppGL.exe
    - 7z a -mx9 dummy_app_%APPVEYOR_BUILD_VERSION%.zip DummyAppVK.exe
    - 7z a -mx9 dummy_app_%APPVEYOR_BUILD_VERSION%.zip assets_pc
    
test_script:
    - build_gl\src\Eng\_tests\%CONFIGURATION%\test_Eng
    - build_gl\src\Ray\tests\%CONFIGURATION%\test_Ray
#    - build_gl\src\Ren\tests\%CONFIGURATION%\test_Ren
    - build_gl\src\Ren\SW\tests\%CONFIGURATION%\test_SW
    - build_gl\src\Sys\tests\%CONFIGURATION%\test_Sys
    - build_gl\src\DummyLib\tests\%CONFIGURATION%\test_DummyLib
    
artifacts:
  - path: dummy_app_%APPVEYOR_BUILD_VERSION%.zip
    name: DummyApp
