stages:
  - build
  - test
  - deploy

.windows-x86_64-gl-build-rel-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - |
      function Invoke-Environment {
        param
        (
            # Any cmd shell command, normally a configuration batch file.
            [Parameter(Mandatory=$true)]
            [string] $Command
        )

        $Command = "`"" + $Command + "`""
        cmd /c "$Command > nul 2>&1 && set" | . { process {
            if ($_ -match '^([^=]+)=(.*)') {
                [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
            }
        }}
      }
    - 'if (Test-Path "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat") { Invoke-Environment "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" }'
    - 'if (Test-Path "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat") { Invoke-Environment "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" }'
    - mkdir build_gl
    - cd build_gl
    - cmake .. -G "Ninja" -DRENDERER=GL -DENABLE_UNITYBUILD=ON -DCMAKE_BUILD_TYPE=Release
    - cd ..
    - cmake --build build_gl --config Release --parallel 16
    - echo "Compile complete."
    - mkdir windows-x86_64-gl
    - copy build_gl/src/Eng/_tests/test_Eng.exe windows-x86_64-gl
    - copy build_gl/src/Ray/tests/test_Ray.exe windows-x86_64-gl
    - copy build_gl/src/Ren/tests/test_Ren.exe windows-x86_64-gl
    - copy build_gl/src/Ren/SW/tests/test_SW.exe windows-x86_64-gl
    - copy build_gl/src/Sys/tests/test_Sys.exe windows-x86_64-gl
    - copy build_gl/src/Net/tests/test_Net.exe windows-x86_64-gl
    - copy build_gl/src/DummyLib/tests/test_DummyLib.exe windows-x86_64-gl
    - copy DummyAppGL.exe windows-x86_64-gl
  artifacts:
    name: windows-x86_64-gl
    paths:
      - windows-x86_64-gl/
    expire_in: 1 week

.windows-x86_64-gl-build-dbg-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - mkdir build_gl
    - cd build_gl
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DRENDERER=GL -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_gl --target ALL_BUILD --config Debug --parallel 16
    - echo "Compile complete."

.windows-x86_64-gl-build-dev-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - mkdir build_gl
    - cd build_gl
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DRENDERER=GL -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_gl --target ALL_BUILD --config RelWithDebInfo --parallel 16
    - echo "Compile complete."

.windows-x86_64-vk-build-rel-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - |
      function Invoke-Environment {
        param
        (
            # Any cmd shell command, normally a configuration batch file.
            [Parameter(Mandatory=$true)]
            [string] $Command
        )

        $Command = "`"" + $Command + "`""
        cmd /c "$Command > nul 2>&1 && set" | . { process {
            if ($_ -match '^([^=]+)=(.*)') {
                [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
            }
        }}
      }
    - 'if (Test-Path "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat") { Invoke-Environment "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" }'
    - 'if (Test-Path "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat") { Invoke-Environment "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" }'
    - mkdir build_vk
    - cd build_vk
    - cmake .. -G "Ninja" -DRENDERER=VK -DENABLE_UNITYBUILD=ON -DCMAKE_BUILD_TYPE=Release
    - cd ..
    - cmake --build build_vk --target DummyApp test_Eng test_Ray test_Ren test_SW test_Sys test_Net test_DummyLib --config Release --parallel 16
    - echo "Compile complete."
    - mkdir windows-x86_64-vk
    - copy build_vk/src/Eng/_tests/test_Eng.exe windows-x86_64-vk
    - copy build_vk/src/Ray/tests/test_Ray.exe windows-x86_64-vk
    - copy build_vk/src/Ren/tests/test_Ren.exe windows-x86_64-vk
    - copy build_vk/src/Ren/SW/tests/test_SW.exe windows-x86_64-vk
    - copy build_vk/src/Sys/tests/test_Sys.exe windows-x86_64-vk
    - copy build_vk/src/Net/tests/test_Net.exe windows-x86_64-vk
    - copy build_vk/src/DummyLib/tests/test_DummyLib.exe windows-x86_64-vk
    - copy DummyAppVK.exe windows-x86_64-vk
  artifacts:
    name: windows-x86_64-vk
    paths:
      - windows-x86_64-vk/
    expire_in: 1 week

.windows-x86_64-vk-build-dbg-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - mkdir build_vk
    - cd build_vk
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DRENDERER=VK -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_vk --target DummyApp test_Eng test_Ray test_Ren test_SW test_Sys test_Net test_DummyLib --config Debug --parallel 16
    - echo "Compile complete."

.windows-x86_64-vk-build-dev-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - mkdir build_vk
    - cd build_vk
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DRENDERER=VK -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_vk --target DummyApp test_Eng test_Ray test_Ren test_SW test_Sys test_Net test_DummyLib --config RelWithDebInfo --parallel 16
    - echo "Compile complete."

.linux-x86_64-gl-build-rel-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling the code..."
    - mkdir build_gl
    - cd build_gl
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DRENDERER=GL -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_gl --target DummyApp test_Eng test_Ray test_Ren test_SW test_Sys test_Net test_DummyLib --parallel 16
    - echo "Compile complete."
    - mkdir linux-x86_64-gl
    - cp build_gl/src/Eng/_tests/test_Eng linux-x86_64-gl
    - cp build_gl/src/Ray/tests/test_Ray linux-x86_64-gl
    - cp build_gl/src/Ren/tests/test_Ren linux-x86_64-gl
    - cp build_gl/src/Ren/SW/tests/test_SW linux-x86_64-gl
    - cp build_gl/src/Sys/tests/test_Sys linux-x86_64-gl
    - cp build_gl/src/Net/tests/test_Net linux-x86_64-gl
    - cp build_gl/src/DummyLib/tests/test_DummyLib linux-x86_64-gl
    - cp DummyAppGL linux-x86_64-gl
  artifacts:
    name: linux-x86_64-gl
    paths:
      - linux-x86_64-gl/
    expire_in: 1 week

.linux-x86_64-gl-build-dbg-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling the code..."
    - mkdir build_gl_dbg
    - cd build_gl_dbg
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DRENDERER=GL -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_gl_dbg --target DummyApp test_Eng test_Ray test_Ren test_SW test_Sys test_Net test_DummyLib --parallel 16
    - echo "Compile complete."

.linux-x86_64-gl-build-dev-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling the code..."
    - mkdir build_gl_dev
    - cd build_gl_dev
    - cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DRENDERER=GL -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_gl_dev --target DummyApp test_Eng test_Ray test_Ren test_SW test_Sys test_Net test_DummyLib --parallel 16
    - echo "Compile complete."

.linux-x86_64-vk-build-rel-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling the code..."
    - mkdir build_vk
    - cd build_vk
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DRENDERER=VK -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_vk --target DummyApp test_Eng test_Ray test_Ren test_SW test_Sys test_Net test_DummyLib --parallel 16
    - echo "Compile complete."
    - mkdir linux-x86_64-vk
    - cp build_vk/src/Eng/_tests/test_Eng linux-x86_64-vk
    - cp build_vk/src/Ray/tests/test_Ray linux-x86_64-vk
    - cp build_vk/src/Ren/tests/test_Ren linux-x86_64-vk
    - cp build_vk/src/Ren/SW/tests/test_SW linux-x86_64-vk
    - cp build_vk/src/Sys/tests/test_Sys linux-x86_64-vk
    - cp build_vk/src/Net/tests/test_Net linux-x86_64-vk
    - cp build_vk/src/DummyLib/tests/test_DummyLib linux-x86_64-vk
    - cp DummyAppVK linux-x86_64-vk
  artifacts:
    name: linux-x86_64-vk
    paths:
      - linux-x86_64-vk/
    expire_in: 1 week

.linux-x86_64-vk-build-dbg-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling the code..."
    - mkdir build_vk_dbg
    - cd build_vk_dbg
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DRENDERER=VK -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_vk_dbg --target DummyApp test_Eng test_Ray test_Ren test_SW test_Sys test_Net test_DummyLib --parallel 16
    - echo "Compile complete."

.linux-x86_64-vk-build-dev-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling the code..."
    - mkdir build_vk_dev
    - cd build_vk_dev
    - cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DRENDERER=VK -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_vk_dev --target DummyApp test_Eng test_Ray test_Ren test_SW test_Sys test_Net test_DummyLib --parallel 16
    - echo "Compile complete."

.macos-build-job:
  stage: build
  tags:
    - macos
  script:
    - echo "Compiling the code..."
    - mkdir build_vk
    - cd build_vk
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DRENDERER=VK -DENABLE_UNITYBUILD=ON
    - cd ..
    - mkdir build_vk_dbg
    - cd build_vk_dbg
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DRENDERER=VK -DENABLE_UNITYBUILD=ON
    - cd ..
    - mkdir build_vk_dev
    - cd build_vk_dev
    - cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DRENDERER=VK -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_vk --target DummyApp test_Eng test_Ray test_SW test_Sys test_Net test_DummyLib --parallel 8
    - cmake --build build_vk_dbg --target DummyApp test_Eng test_Ray test_SW test_Sys test_Net test_DummyLib --parallel 8
    - cmake --build build_vk_dev --target DummyApp test_Eng test_Ray test_SW test_Sys test_Net test_DummyLib --parallel 8
    - echo "Compile complete."
#  artifacts:
#    paths:
#      - build_vk/
#      - DummyAppVK

.windows-test-job-common:
  stage: test
  script:
    - echo "Running tests..."
    - '& "$BIN_DIR/test_SW"'
    - '& "$BIN_DIR/test_Sys"'
    - '& "$BIN_DIR/test_Net"'

.windows-test-job-gl:
  stage: test
  script:
    - echo "Running GL tests..."
    - '& "$BIN_DIR/test_Eng"'
    - '& "$BIN_DIR/test_Ren"'
    - '& "$BIN_DIR/test_DummyLib"'

.windows-test-job-vk:
  stage: test
  script:
    - echo "Running VK tests..."
    - '& "$BIN_DIR/test_Eng"'
    - '& "$BIN_DIR/test_Ren"'
    - '& "$BIN_DIR/test_DummyLib"'

.linux-test-job-common:
  stage: test
  script:
    - echo "Running tests..."
    - $BIN_DIR/test_SW
    - $BIN_DIR/test_Sys
    - $BIN_DIR/test_Net

.linux-test-job-gl:
  stage: test
  script:
    - echo "Running GL tests..."
    - $BIN_DIR/test_Eng
    - $BIN_DIR/test_Ren
    - $BIN_DIR/test_DummyLib

.linux-test-job-vk:
  stage: test
  script:
    - echo "Running VK tests..."
    - $BIN_DIR/test_Eng
    - $BIN_DIR/test_Ren
    - $BIN_DIR/test_DummyLib

windows-x86_64-gl-build-rel-job:
  extends:
    - .windows-x86_64-gl-build-rel-job
  tags:
    - builder,windows,x86_64

windows-x86_64-gl-build-dbg-job:
  extends:
    - .windows-x86_64-gl-build-dbg-job
  tags:
    - builder,windows,x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

windows-x86_64-gl-build-dev-job:
  extends:
    - .windows-x86_64-gl-build-dev-job
  tags:
    - builder,windows,x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

windows-x86_64-vk-build-rel-job:
  extends:
    - .windows-x86_64-vk-build-rel-job
  tags:
    - builder,windows,x86_64

windows-x86_64-vk-build-dbg-job:
  extends:
    - .windows-x86_64-vk-build-dbg-job
  tags:
    - builder,windows,x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

windows-x86_64-vk-build-dev-job:
  extends:
    - .windows-x86_64-vk-build-dev-job
  tags:
    - builder,windows,x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

linux-x86_64-gl-build-rel-job:
  extends:
    - .linux-x86_64-gl-build-rel-job
  tags:
    - builder,linux,x86_64

linux-x86_64-gl-build-dbg-job:
  extends:
    - .linux-x86_64-gl-build-dbg-job
  tags:
    - builder,linux,x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

linux-x86_64-gl-build-dev-job:
  extends:
    - .linux-x86_64-gl-build-dev-job
  tags:
    - builder,linux,x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

linux-x86_64-vk-build-rel-job:
  extends:
    - .linux-x86_64-vk-build-rel-job
  tags:
    - builder,linux,x86_64

linux-x86_64-vk-build-dbg-job:
  extends:
    - .linux-x86_64-vk-build-dbg-job
  tags:
    - builder,linux,x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

linux-x86_64-vk-build-dev-job:
  extends:
    - .linux-x86_64-vk-build-dev-job
  tags:
    - builder,linux,x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

windows-x86_64-test-job-common:
  variables:
    BIN_DIR: windows-x86_64-vk
  stage: test
  extends:
    - .windows-test-job-common
  needs:
    - windows-x86_64-vk-build-rel-job
  tags:
    - windows,x86_64

windows-x86_64-test-job-gl:
  variables:
    BIN_DIR: windows-x86_64-gl
  stage: test
  extends:
    - .windows-test-job-gl
  needs:
    - windows-x86_64-gl-build-rel-job
  tags:
    - windows,x86_64

windows-x86_64-test-job-vk:
  variables:
    BIN_DIR: windows-x86_64-vk
  stage: test
  extends:
    - .windows-test-job-vk
  needs:
    - windows-x86_64-vk-build-rel-job
  tags:
    - windows,x86_64

linux-x86_64-test-job-common:
  variables:
    BIN_DIR: linux-x86_64-vk
  stage: test
  extends:
    - .linux-test-job-common
  needs:
    - linux-x86_64-vk-build-rel-job
  tags:
    - linux,x86_64

linux-x86_64-test-job-gl:
  variables:
    BIN_DIR: linux-x86_64-gl
  stage: test
  extends:
    - .linux-test-job-gl
  needs:
    - linux-x86_64-gl-build-rel-job
  tags:
    - linux,x86_64

linux-x86_64-test-job-vk:
  variables:
    BIN_DIR: linux-x86_64-vk
  stage: test
  extends:
    - .linux-test-job-vk
  needs:
    - linux-x86_64-vk-build-rel-job
  tags:
    - linux,x86_64

deploy-job:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  needs:
    - windows-x86_64-test-job-common
    - windows-x86_64-test-job-gl
    - windows-x86_64-test-job-vk
    - linux-x86_64-test-job-common
    - linux-x86_64-test-job-gl
    - linux-x86_64-test-job-vk
  script:
    - echo "Deploying application..."
#    - ./DummyAppVK --prepare_assets pc --norun
#    - 7z a -mx9 dummy_app.zip DummyAppGL.exe
#    - 7z a -mx9 dummy_app.zip DummyAppVK.exe
#    - 7z a -mx9 dummy_app.zip assets_pc
    - echo "Application successfully deployed."
  artifacts:
    paths:
      - dummy_app.zip
  tags:
    - windows

