name: 'Test Img'
inputs:
  bin-name:
    required: true
  bin-dir:
    required: true
  out-dir:
    required: true
  test-args:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        chmod +x ./${{ inputs.bin-dir }}/${{ inputs.bin-name }}
        WORK_DIR=`pwd`
        cd ../../builds/DummyEngine/assets/shaders
        ln -s ../../src/Eng/renderer/shaders internal
        cd ../textures
        ln -s ../../src/Eng/renderer/textures internal
        cd ../../
        cp $WORK_DIR/${{ inputs.bin-dir }}/${{ inputs.bin-name }} ./
        mkdir $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} --prepare_assets pc --norun
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro.uncompressed.png -w 1920 -h 1080 --exposure -11 --preset medium --psnr 21.40
        mv bistro.png bistro_medium.png
        mv bistro_diff.png bistro_diff_medium.png
        cp bistro_medium.png bistro_diff_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro.uncompressed.png -w 1920 -h 1080 --exposure -11 --preset high --psnr 22.00
        mv bistro.png bistro_high.png
        mv bistro_diff.png bistro_diff_high.png
        cp bistro_high.png bistro_diff_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro.uncompressed.png -w 1920 -h 1080 --exposure -11 --preset ultra --psnr 25.30
        mv bistro.png bistro_ultra.png
        mv bistro_diff.png bistro_diff_ultra.png
        cp bistro_ultra.png bistro_diff_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza.uncompressed.png -w 1920 -h 1080 --exposure -8 --preset medium --psnr 21.55
        mv sponza.png sponza_medium.png
        mv sponza_diff.png sponza_diff_medium.png
        cp sponza_medium.png sponza_diff_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza.uncompressed.png -w 1920 -h 1080 --exposure -8 --preset high --psnr 22.15
        mv sponza.png sponza_high.png
        mv sponza_diff.png sponza_diff_high.png
        cp sponza_high.png sponza_diff_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza.uncompressed.png -w 1920 -h 1080 --exposure -8 --preset ultra --psnr 23.75
        mv sponza.png sponza_ultra.png
        mv sponza_diff.png sponza_diff_ultra.png
        cp sponza_ultra.png sponza_diff_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06.uncompressed.png -w 1400 -h 936 --preset medium --psnr 21.75
        mv ai043_06.png ai043_06_medium.png
        mv ai043_06_diff.png ai043_06_diff_medium.png
        cp ai043_06_medium.png ai043_06_diff_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06.uncompressed.png -w 1400 -h 936 --preset high --psnr 24.60
        mv ai043_06.png ai043_06_high.png
        mv ai043_06_diff.png ai043_06_diff_high.png
        cp ai043_06_high.png ai043_06_diff_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06.uncompressed.png -w 1400 -h 936 --preset ultra --psnr 25.60
        mv ai043_06.png ai043_06_ultra.png
        mv ai043_06_diff.png ai043_06_diff_ultra.png
        cp ai043_06_ultra.png ai043_06_diff_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06.uncompressed.png -w 1400 -h 936 --pt --psnr 23.35
        mv ai043_06.png ai043_06_pt.png
        mv ai043_06_diff.png ai043_06_diff_pt.png
        cp ai043_06_pt.png ai043_06_diff_pt.png $WORK_DIR/${{ inputs.out-dir }}
      shell: bash
