name: 'Test Img'
inputs:
  bin-name:
    required: true
  bin-dir:
    required: true
  out-dir:
    required: true
  test-args:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        chmod +x ./${{ inputs.bin-dir }}/${{ inputs.bin-name }}
        WORK_DIR=`pwd`
        cd ../../builds/DummyEngine/assets/shaders
        ln -s ../../src/Eng/renderer/shaders internal
        cd ../textures
        ln -s ../../src/Eng/renderer/textures internal
        cd ../../
        cp $WORK_DIR/${{ inputs.bin-dir }}/${{ inputs.bin-name }} ./
        mkdir $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} --prepare_assets pc --norun
        ### Coffee maker
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/coffee_maker.json -ref references/coffee_maker_cycles.uncompressed.png -w 800 -h 1000 --preset medium --psnr 23.60
        mv coffee_maker.png coffee_maker_medium.png
        mv coffee_maker_diff.png coffee_maker_diff_medium.png
        cp coffee_maker_medium.png coffee_maker_diff_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/coffee_maker.json -ref references/coffee_maker_cycles.uncompressed.png -w 800 -h 1000 --preset high --psnr 24.25
        mv coffee_maker.png coffee_maker_high.png
        mv coffee_maker_diff.png coffee_maker_diff_high.png
        cp coffee_maker_high.png coffee_maker_diff_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/coffee_maker.json -ref references/coffee_maker_cycles.uncompressed.png -w 800 -h 1000 --preset ultra --psnr 24.45
        mv coffee_maker.png coffee_maker_ultra.png
        mv coffee_maker_diff.png coffee_maker_diff_ultra.png
        cp coffee_maker_ultra.png coffee_maker_diff_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ### Staircase
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --preset medium --psnr 26.30
        mv staircase.png staircase_medium.png
        mv staircase_diff.png staircase_diff_medium.png
        cp staircase_medium.png staircase_diff_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --preset high --psnr 26.95
        mv staircase.png staircase_high.png
        mv staircase_diff.png staircase_diff_high.png
        cp staircase_high.png staircase_diff_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --preset ultra --psnr 27.40
        mv staircase.png staircase_ultra.png
        mv staircase_diff.png staircase_diff_ultra.png
        cp staircase_ultra.png staircase_diff_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ### Bistro
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_cycles.uncompressed.png -w 1920 -h 1080 --exposure -11 --preset medium --psnr 21.40
        mv bistro.png bistro_medium.png
        mv bistro_diff.png bistro_diff_medium.png
        cp bistro_medium.png bistro_diff_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_cycles.uncompressed.png -w 1920 -h 1080 --exposure -11 --preset high --psnr 22.09
        mv bistro.png bistro_high.png
        mv bistro_diff.png bistro_diff_high.png
        cp bistro_high.png bistro_diff_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_cycles.uncompressed.png -w 1920 -h 1080 --exposure -11 --preset ultra --psnr 25.50
        mv bistro.png bistro_ultra.png
        mv bistro_diff.png bistro_diff_ultra.png
        cp bistro_ultra.png bistro_diff_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ### Sponza
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_cycles.uncompressed.png -w 1920 -h 1080 --exposure -8 --preset medium --psnr 21.50
        mv sponza.png sponza_medium.png
        mv sponza_diff.png sponza_diff_medium.png
        cp sponza_medium.png sponza_diff_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_cycles.uncompressed.png -w 1920 -h 1080 --exposure -8 --preset high --psnr 22.55
        mv sponza.png sponza_high.png
        mv sponza_diff.png sponza_diff_high.png
        cp sponza_high.png sponza_diff_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_cycles.uncompressed.png -w 1920 -h 1080 --exposure -8 --preset ultra --psnr 24.30
        mv sponza.png sponza_ultra.png
        mv sponza_diff.png sponza_diff_ultra.png
        cp sponza_ultra.png sponza_diff_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ### ai043_06
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06_cycles.uncompressed.png -w 1400 -h 936 --preset medium --psnr 20.15
        mv ai043_06.png ai043_06_medium.png
        mv ai043_06_diff.png ai043_06_diff_medium.png
        cp ai043_06_medium.png ai043_06_diff_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06_cycles.uncompressed.png -w 1400 -h 936 --preset high --psnr 19.20
        mv ai043_06.png ai043_06_high.png
        mv ai043_06_diff.png ai043_06_diff_high.png
        cp ai043_06_high.png ai043_06_diff_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06_cycles.uncompressed.png -w 1400 -h 936 --preset ultra --psnr 20.70
        mv ai043_06.png ai043_06_ultra.png
        mv ai043_06_diff.png ai043_06_diff_ultra.png
        cp ai043_06_ultra.png ai043_06_diff_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06_cycles.uncompressed.png -w 1400 -h 936 --pt --psnr 32.75
        mv ai043_06.png ai043_06_pt.png
        mv ai043_06_diff.png ai043_06_diff_pt.png
        cp ai043_06_pt.png ai043_06_diff_pt.png $WORK_DIR/${{ inputs.out-dir }}
      shell: bash
