name: 'Test Img'
inputs:
  bin-name:
    required: true
  bin-dir:
    required: true
  out-dir:
    required: true
  test-args:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        chmod +x ./${{ inputs.bin-dir }}/${{ inputs.bin-name }}
        WORK_DIR=`pwd`
        cd ../../builds/DummyEngine/assets/shaders
        ln -s ../../src/Eng/renderer/shaders internal
        cd ../textures
        ln -s ../../src/Eng/renderer/textures internal
        cd ../../
        cp $WORK_DIR/${{ inputs.bin-dir }}/${{ inputs.bin-name }} ./
        mkdir $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} --prepare_assets pc --norun
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza.uncompressed.png -w 1920 -h 1080 --exposure -8 --psnr 21.32
        cp sponza.png sponza_diff.png $WORK_DIR/${{ inputs.out-dir }}
        #./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza.uncompressed.png -w 1920 -h 1080 --exposure -8 --pt --psnr 27.58
        #mv sponza.png sponza_pt.png
        #mv sponza_diff.png sponza_diff_pt.png
        #cp sponza_pt.png sponza_diff_pt.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06.uncompressed.png -w 1400 -h 936 --psnr 21.73
        cp ai043_06.png ai043_06_diff.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06.uncompressed.png -w 1400 -h 936 --pt --psnr 23.37
        mv ai043_06.png ai043_06_pt.png
        mv ai043_06_diff.png ai043_06_diff_pt.png
        cp ai043_06_pt.png ai043_06_diff_pt.png $WORK_DIR/${{ inputs.out-dir }}
      shell: bash
